In [12]:
# 导入numpy，别名为np。
import numpy as np

In [13]:
整数范围数组 = np.arange(10)        # 创建从0到10（不包括10）的一个范围数组
print(整数范围数组) 

[0 1 2 3 4 5 6 7 8 9]


In [18]:
# 创建从0到10（不包括10）的整数范围，步长为2。
带步长的整数范围数组 = np.arange(start = 0, stop = 10, step = 2, dtype = 'int') 

print(带步长的整数范围数组) 

[0 2 4 6 8]


In [8]:
# 创建从0到10的一个浮点数范围，步长为0.5。
带步长的浮点数范围数组 = np.arange(0, 10, 0.5) 
print(带步长的浮点数范围数组) 

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [19]:
print(整数范围数组.ndim), print(整数范围数组.shape), print(整数范围数组.size);

1
(10,)
10


In [9]:
一维全零数组 = np.zeros(5)          # 创建一个都是0的数组。

print(一维全零数组)
print(一维全零数组.shape)

[0. 0. 0. 0. 0.]
(5,)


In [13]:
二维全零数组 = np.zeros((2,3))      # 创建一个都是0的2行、3列二维数组。

print(二维全零数组), print(二维全零数组.shape);

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [14]:
填满一个数的数组 = np.full((2, 3), 8)    # 用8填满一个形状为(2, 3)的数组。
print(填满一个数的数组)

[[8 8 8]
 [8 8 8]]


In [3]:
四阶单位矩阵 = np.eye(4)            # 创建一个4x4的单位矩阵。
print(四阶单位矩阵)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
四阶整型单位矩阵 = np.eye(4, dtype = 'int')   # 创建一个4x4的整数型单位矩阵。
print(四阶整型单位矩阵)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [4]:
随机数数组 = np.random.random((2, 4)) # 带有随机值（在范围[0.0, 1.0)内）的2行4列数组。
print(随机数数组)

[[0.28163028 0.2955566  0.34532784 0.80386192]
 [0.67077075 0.6617618  0.52139717 0.85194722]]


In [21]:
一个Python列表 = [[1, 2, 3, 4, 5], 
                 [2, 3, 4, 5, 6],
                 [3, 2, 1, 6, 5],
                 [5, 6, 4, 3, 1]]

转换的NumPy数组 = np.array(一个Python列表)

print(转换的NumPy数组.ndim)
print(转换的NumPy数组.shape)
print(转换的NumPy数组.size)

2
(4, 5)
20


In [7]:
print(转换的NumPy数组[0])
print(转换的NumPy数组[1])

1
2


In [8]:
print(转换的NumPy数组[-1])
print(转换的NumPy数组[-2])

5
4


In [9]:
第二个Python列表 = [6,7,8,9,0]
转换的二维NumPy数组 = np.array([一个Python列表, 第二个Python列表])

print(转换的二维NumPy数组)
print(转换的二维NumPy数组.shape)

print(转换的二维NumPy数组[0,0])
print(转换的二维NumPy数组[0,1])
print(转换的二维NumPy数组[1,0])

[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)
1
2
6


In [13]:
print(转换的NumPy数组[[2, 4]])

[3 5]


In [15]:
print(转换的二维NumPy数组[[0, 1], [1, 3]])

[2 9]


In [13]:
print(转换的NumPy数组 > 2)     # 返回数组中所有大于2的元素位置。

[False False  True  True  True]


In [16]:
print(转换的NumPy数组[转换的NumPy数组 > 2])

[3 4 5]


In [17]:
一个整数范围的数组 = np.arange(20)
print(一个整数范围的数组)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [18]:
数组中的奇数 = 一个整数范围的数组[一个整数范围的数组 % 2 == 1]
print(数组中的奇数)

[ 1  3  5  7  9 11 13 15 17 19]


In [19]:
一个二维NumPy数组 = np.array([[1, 2, 3, 4, 5],
                             [4, 5, 6, 7, 8],
                             [9, 8, 7, 6, 5]])
print(一个二维NumPy数组)

[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]


In [20]:
第一个切片 = 一个二维NumPy数组[1:3, :3]
print(第一个切片)

[[4 5 6]
 [9 8 7]]


In [21]:
第二个切片 = 一个二维NumPy数组[-2:,-2:]
print(第二个切片)

[[7 8]
 [6 5]]


In [24]:
原始二维数组 = np.array([[1, 2, 3, 4],
                        [4, 5, 6, 7],
                        [9, 8, 7, 6]])

print(原始二维数组)
print(原始二维数组.shape)

[[1 2 3 4]
 [4 5 6 7]
 [9 8 7 6]]
(3, 4)


In [26]:
重塑后的二维数组 = 原始二维数组.reshape(4, 3)
print(重塑后的二维数组)

[[1 2 3]
 [4 4 5]
 [6 7 9]
 [8 7 6]]


In [28]:
自动确定列数的重塑数组 = 原始二维数组.reshape(4, -1)

print(自动确定列数的重塑数组)

[[1 2 3]
 [4 4 5]
 [6 7 9]
 [8 7 6]]


In [29]:
自动确定行数的重塑数组 = 原始二维数组.reshape(-1, 6)

print(自动确定行数的重塑数组)

[[1 2 3 4 4 5]
 [6 7 9 8 7 6]]


In [30]:
自动确定形状的重塑数组 = 原始二维数组.reshape(-1, -1)

print(自动确定形状的重塑数组)

ValueError: can only specify one unknown dimension

In [31]:
指定形状的重塑数组 = 原始二维数组.reshape(3, 5)

print(指定形状的重塑数组)

ValueError: cannot reshape array of size 12 into shape (3,5)

In [22]:
# 创建二个Python列表
距离列表 = [100, 115, 117, 206, 120]
时间列表 = [1.3, 1.27, 3.58, 9.20, 8.0]

距离数组 = np.array(距离列表)
时间数组 = np.array(时间列表)

In [25]:
速度数组 = 距离数组/时间数组
速度数组    # print(速度数组)输出为列表形式

array([76.92307692, 90.5511811 , 32.68156425, 22.39130435, 15.        ])

In [26]:
# NumPy的通用函数sin作用于数组
np.sin(距离数组)

array([-0.50636564,  0.94543533, -0.68969794, -0.9746419 ,  0.58061118])

In [27]:
from math import sin
# Python标准库中的sin函数（及其它函数）不能作用于NumPy数组。

sin(距离数组)

TypeError: only size-1 arrays can be converted to Python scalars

In [30]:
# 使用随机数模拟抛掷一枚硬币
# 使用随机生成整数0或1，模拟投掷一枚硬币：0代表背面，1代表正面。
np.random.randint(low = 0, high = 2, size = 1)

array([1])

In [34]:
# 连续投掷一枚硬币10次作为一次随机实验。
一次抛掷硬币实验 = np.random.randint(0, 2, size = 10)
print(一次抛掷硬币实验)           # 显示实验结果
print(一次抛掷硬币实验.sum())     # 显示10次抛掷中，正面朝上的次数。 

[1 1 0 0 0 1 0 1 1 1]
6


In [38]:
# 重复10000次随机实验
重复随机实验 = np.random.randint(0, 2, size = (10000, 10))

# 显示其中前10行。
print(重复随机实验[:10, :]) 

[[0 1 1 1 0 1 0 0 1 0]
 [1 1 1 1 1 0 1 0 0 1]
 [1 0 1 0 1 0 0 0 1 1]
 [0 0 1 1 1 1 0 0 0 0]
 [1 1 1 0 0 0 0 0 1 1]
 [0 0 1 1 0 1 1 0 0 1]
 [1 0 1 1 0 1 1 1 0 1]
 [0 0 0 1 0 1 1 1 1 0]
 [1 1 1 0 1 1 0 0 0 1]
 [0 1 0 0 0 1 0 0 0 1]]


In [37]:
# 一些基本计数和统计
出现正面次数 = 重复随机实验.sum(axis = 1)    # axis = 1表示对每个列求和。

# 10000次实验中，每次随机实验中出现正面次数的平均值。
print(出现正面次数.mean())

# 10000次实验中，每次随机实验出现正面次数的中位数。
print(np.median(出现正面次数))              

# 10000次实验中，每次随机实验出现正面次数的最小值和最大值。
print(出现正面次数.min(), 出现正面次数.max())     

# 10000次实验中，每次随机实验中出现正面次数的标准差。
print(出现正面次数.std())

5.0127
5.0
0 10
1.5814356483904113


In [40]:
一次随机实验抛掷次数 = np.arange(0, 11)
观察到的次数 = np.bincount(出现正面次数)

print("===============\n")
for n, count in zip(一次随机实验抛掷次数, 观察到的次数):
    print("第{}次抛掷，共观察到正面：{}次 ({:0.1f}%)".format(n, count, 100 * count/10000))


第0次抛掷，共观察到正面：13次 (0.1%)
第1次抛掷，共观察到正面：117次 (1.2%)
第2次抛掷，共观察到正面：419次 (4.2%)
第3次抛掷，共观察到正面：1140次 (11.4%)
第4次抛掷，共观察到正面：1983次 (19.8%)
第5次抛掷，共观察到正面：2531次 (25.3%)
第6次抛掷，共观察到正面：2055次 (20.6%)
第7次抛掷，共观察到正面：1227次 (12.3%)
第8次抛掷，共观察到正面：399次 (4.0%)
第9次抛掷，共观察到正面：106次 (1.1%)
第10次抛掷，共观察到正面：10次 (0.1%)


In [42]:
# 从列表创建
气温 = [23, 19, 15, 9, 11, -5, 9]
日期 = ['星期一','星期二','星期三','星期四','星期五','星期六','星期日']

# 创建Series对象：列表“气温”作为数据，列表“日期”作为索引。 
从列表创建Series对象 = pd.Series(气温, index = 日期)
从列表创建Series对象

星期一    23
星期二    19
星期三    15
星期四     9
星期五    11
星期六    -5
星期日     9
dtype: int64

In [43]:
# 从字典创建

字典 = {'星期一': 23, '星期二': 19, '星期三': 15, 
        '星期四': 9, '星期五': 11, '星期六': -5, '星期日': 9}

# 创建Series对象：字典值作为数据，字典关键词作为索引。 
从字典创建Series对象 = pd.Series(字典)
从字典创建Series对象

星期一    23
星期二    19
星期三    15
星期四     9
星期五    11
星期六    -5
星期日     9
dtype: int64

In [44]:
# 从numpy数组创建
范围数组 = np.linspace(0, 10, 15)

# 创建Series对象：数组中的值作为数据，自动生成默认索引。
从数组创建Series对象 = pd.Series(范围数组)
从数组创建Series对象

0      0.000000
1      0.714286
2      1.428571
3      2.142857
4      2.857143
5      3.571429
6      4.285714
7      5.000000
8      5.714286
9      6.428571
10     7.142857
11     7.857143
12     8.571429
13     9.285714
14    10.000000
dtype: float64

In [74]:
import pandas as pd
import numpy as np

# 使用DataFrame函数直接从数据产生
数据帧的实例 = pd.DataFrame(np.random.randn(10, 4), columns = list('ABCD'))
数据帧的实例

A         B         C         D
0 -0.289250  0.442671 -1.604742  1.327943
1  0.951947  0.335865  2.354530  0.386627
2  0.549082 -0.974809 -0.547286 -1.028474
3  0.342330  1.223685 -2.243039 -0.584495
4 -0.278111 -0.233396  0.695089  0.203179
5  0.042353  1.035513 -1.079720 -0.261004
6 -0.955510  0.715137  0.448686 -0.024740
7  0.957339 -0.554422  0.904310 -0.415632
8  1.426751 -0.893622  1.944360  1.668782
9 -2.323945 -0.133213 -1.317816  0.475373

In [51]:
产生日期范围 = pd.date_range('20191201', periods = 10)   # 生成一个日期范围 
print(产生日期范围)

DatetimeIndex(['2019-12-01', '2019-12-02', '2019-12-03', '2019-12-04',
               '2019-12-05', '2019-12-06', '2019-12-07', '2019-12-08',
               '2019-12-09', '2019-12-10'],
              dtype='datetime64[ns]', freq='D')


In [52]:
数据帧的实例.index = 产生日期范围     # 将日期范围指定为索引
print(数据帧的实例)

                   A         B         C         D
2019-12-01  0.758515 -1.156802 -0.650631 -0.191784
2019-12-02 -1.204874  1.212811 -1.329079 -0.736970
2019-12-03 -0.175898  0.740828 -1.552197  1.187381
2019-12-04 -0.114357  0.111413  1.029002  0.318320
2019-12-05 -2.266612  0.535851  0.345531 -0.943554
2019-12-06  0.350373 -0.816398 -2.093955 -0.056683
2019-12-07  0.348589  0.969589  1.333753  0.329292
2019-12-08 -0.920187  0.238947 -0.808772  0.335439
2019-12-09  1.450891  0.147826  0.247788 -0.121437
2019-12-10 -0.020985  0.418398  0.353591  3.206765


In [53]:
print(数据帧的实例.index)

DatetimeIndex(['2019-12-01', '2019-12-02', '2019-12-03', '2019-12-04',
               '2019-12-05', '2019-12-06', '2019-12-07', '2019-12-08',
               '2019-12-09', '2019-12-10'],
              dtype='datetime64[ns]', freq='D')


In [54]:
print(数据帧的实例.values)

[[ 0.7585152  -1.15680211 -0.65063062 -0.19178445]
 [-1.20487431  1.21281122 -1.32907908 -0.73697036]
 [-0.17589813  0.74082823 -1.55219669  1.1873815 ]
 [-0.11435747  0.11141317  1.02900181  0.31832011]
 [-2.26661207  0.53585052  0.34553123 -0.94355406]
 [ 0.35037259 -0.8163983  -2.0939553  -0.05668317]
 [ 0.34858915  0.96958931  1.33375285  0.3292922 ]
 [-0.92018745  0.23894672 -0.80877166  0.3354389 ]
 [ 1.45089059  0.14782557  0.24778777 -0.12143661]
 [-0.02098466  0.41839763  0.35359126  3.20676526]]


In [55]:
print(数据帧的实例.describe())

               A          B          C          D
count  10.000000  10.000000  10.000000  10.000000
mean   -0.179455   0.240246  -0.312497   0.332677
std     1.058464   0.740939   1.145273   1.173642
min    -2.266612  -1.156802  -2.093955  -0.943554
25%    -0.734115   0.120516  -1.199002  -0.174197
50%    -0.067671   0.328672  -0.201421   0.130818
75%     0.349927   0.689584   0.351576   0.333902
max     1.450891   1.212811   1.333753   3.206765


In [56]:
print(数据帧的实例.mean(axis = 0))    # axis = 0意味着针对每个列计算平均值。

A   -0.179455
B    0.240246
C   -0.312497
D    0.332677
dtype: float64


In [58]:
print(数据帧的实例.mean(axis = 1))   # axis = 1意味着针对每个行计算平均值。

2019-12-01   -0.310175
2019-12-02   -0.514528
2019-12-03    0.050029
2019-12-04    0.336094
2019-12-05   -0.582196
2019-12-06   -0.654166
2019-12-07    0.745306
2019-12-08   -0.288643
2019-12-09    0.431267
2019-12-10    0.989442
Freq: D, dtype: float64


In [61]:
# 获取名为A的列
print(数据帧的实例['A'])

2019-12-01    0.758515
2019-12-02   -1.204874
2019-12-03   -0.175898
2019-12-04   -0.114357
2019-12-05   -2.266612
2019-12-06    0.350373
2019-12-07    0.348589
2019-12-08   -0.920187
2019-12-09    1.450891
2019-12-10   -0.020985
Freq: D, Name: A, dtype: float64


In [60]:
print(数据帧的实例.A)     # 与上一条指令的结果相同。

2019-12-01    0.758515
2019-12-02   -1.204874
2019-12-03   -0.175898
2019-12-04   -0.114357
2019-12-05   -2.266612
2019-12-06    0.350373
2019-12-07    0.348589
2019-12-08   -0.920187
2019-12-09    1.450891
2019-12-10   -0.020985
Freq: D, Name: A, dtype: float64


In [62]:
# 获取名为A、B的两列
print(数据帧的实例[['A', 'B']])

                   A         B
2019-12-01  0.758515 -1.156802
2019-12-02 -1.204874  1.212811
2019-12-03 -0.175898  0.740828
2019-12-04 -0.114357  0.111413
2019-12-05 -2.266612  0.535851
2019-12-06  0.350373 -0.816398
2019-12-07  0.348589  0.969589
2019-12-08 -0.920187  0.238947
2019-12-09  1.450891  0.147826
2019-12-10 -0.020985  0.418398


In [63]:
print(数据帧的实例[2:4])

                   A         B         C         D
2019-12-03 -0.175898  0.740828 -1.552197  1.187381
2019-12-04 -0.114357  0.111413  1.029002  0.318320


In [64]:
print(数据帧的实例.iloc[2:4])      # 同上：抽取第2行到第3行。

                   A         B         C         D
2019-12-03 -0.175898  0.740828 -1.552197  1.187381
2019-12-04 -0.114357  0.111413  1.029002  0.318320


In [65]:
print(数据帧的实例.iloc[3:7])      # 抽取第3、4、5、6行。

                   A         B         C         D
2019-12-04 -0.114357  0.111413  1.029002  0.318320
2019-12-05 -2.266612  0.535851  0.345531 -0.943554
2019-12-06  0.350373 -0.816398 -2.093955 -0.056683
2019-12-07  0.348589  0.969589  1.333753  0.329292


In [67]:
print(数据帧的实例[[2, 4]])     # 显示错误信息；此时必须要使用iloc。

KeyError: "None of [Int64Index([2, 4], dtype='int64')] are in the [columns]"

In [70]:
print(数据帧的实例.iloc[[2, 4]])    # 抽取第2行和第4行。

                   A         B         C         D
2019-12-03 -0.175898  0.740828 -1.552197  1.187381
2019-12-05 -2.266612  0.535851  0.345531 -0.943554


In [71]:
print(数据帧的实例.iloc[4:8, 1:4])

                   B         C         D
2019-12-05  0.535851  0.345531 -0.943554
2019-12-06 -0.816398 -2.093955 -0.056683
2019-12-07  0.969589  1.333753  0.329292
2019-12-08  0.238947 -0.808772  0.335439


In [72]:
print(数据帧的实例.iloc[[2, 4], [1, 3]])

                   B         D
2019-12-03  0.740828  1.187381
2019-12-05  0.535851 -0.943554


In [32]:
print(df[(数据帧的实例.A > 0) & (数据帧的实例.B > 0)])

                   A         B         C         D
2019-09-09  0.187497  1.122150 -0.988277 -1.985934
2019-09-15  0.001268  0.951517  2.107360 -0.108726
2019-09-17  0.387023  1.706336 -2.452653  0.260466


In [36]:
print(数据帧的实例.sort_index(axis = 0, ascending = False))   # axis = 0意味着按照行索引排序。

                   A         B         C         D
2019-09-18 -1.054974  0.556775 -0.945219 -0.030295
2019-09-17  0.387023  1.706336 -2.452653  0.260466
2019-09-16 -0.185258  0.856520 -0.686285  1.104195
2019-09-15  0.001268  0.951517  2.107360 -0.108726
2019-09-14  0.070011 -0.516443 -1.655689  0.246721
2019-09-13  0.537438 -1.737568  0.714727 -0.939288
2019-09-12 -0.279572 -0.702492  0.252265  0.958977
2019-09-11 -0.040627  0.067333 -0.452978  0.686223
2019-09-10  0.360803 -0.562243 -0.340693 -0.986988
2019-09-09  0.187497  1.122150 -0.988277 -1.985934


In [37]:
print(数据帧的实例.sort_index(axis = 1, ascending = False))  # axis = 1意味着按照列来排序。

                   D         C         B         A
2019-09-09 -1.985934 -0.988277  1.122150  0.187497
2019-09-10 -0.986988 -0.340693 -0.562243  0.360803
2019-09-11  0.686223 -0.452978  0.067333 -0.040627
2019-09-12  0.958977  0.252265 -0.702492 -0.279572
2019-09-13 -0.939288  0.714727 -1.737568  0.537438
2019-09-14  0.246721 -1.655689 -0.516443  0.070011
2019-09-15 -0.108726  2.107360  0.951517  0.001268
2019-09-16  1.104195 -0.686285  0.856520 -0.185258
2019-09-17  0.260466 -2.452653  1.706336  0.387023
2019-09-18 -0.030295 -0.945219  0.556775 -1.054974


In [48]:
print(数据帧的实例.sort_values('A', axis = 0))    # 基于A列的值来排序，默认为升序。

                   A         B         C         D
2019-06-03 -1.054974  0.556775 -0.945219 -0.030295
2019-05-28 -0.279572 -0.702492  0.252265  0.958977
2019-06-01 -0.185258  0.856520 -0.686285  1.104195
2019-05-27 -0.040627  0.067333 -0.452978  0.686223
2019-05-31  0.001268  0.951517  2.107360 -0.108726
2019-05-30  0.070011 -0.516443 -1.655689  0.246721
2019-05-25  0.187497  1.122150 -0.988277 -1.985934
2019-05-26  0.360803 -0.562243 -0.340693 -0.986988
2019-06-02  0.387023  1.706336 -2.452653  0.260466
2019-05-29  0.537438 -1.737568  0.714727 -0.939288


如果是基于一个特定的行索引来排序，需将参数`axis`设为1：

In [38]:
print(数据帧的实例.sort_values('20191207', axis = 1))

                   C         A         B         D
2019-09-09 -0.988277  0.187497  1.122150 -1.985934
2019-09-10 -0.340693  0.360803 -0.562243 -0.986988
2019-09-11 -0.452978 -0.040627  0.067333  0.686223
2019-09-12  0.252265 -0.279572 -0.702492  0.958977
2019-09-13  0.714727  0.537438 -1.737568 -0.939288
2019-09-14 -1.655689  0.070011 -0.516443  0.246721
2019-09-15  2.107360  0.001268  0.951517 -0.108726
2019-09-16 -0.686285 -0.185258  0.856520  1.104195
2019-09-17 -2.452653  0.387023  1.706336  0.260466
2019-09-18 -0.945219 -1.054974  0.556775 -0.030295


In [1]:
import numpy as np
import pandas as pd

字典 = {'年份': [2010, 2011, 2012, 2010, 2011, 2012, 2010, 2011, 2012],
        '俱乐部': ['巴塞罗那', '巴塞罗那', '巴塞罗那', '皇家马德里', '皇家马德里', '皇家马德里', '瓦伦西亚',
                 '瓦伦西亚', '瓦伦西亚'],
        '胜': [30, 28, 32, 29, 32, 26, 21, 17, 19],
        '平': [6, 7, 4, 5, 4, 7, 8, 10, 8],
        '负': [2, 3, 2, 4, 2, 5, 9, 11, 11]
        }
历年成绩表 = pd.DataFrame(字典, columns = ['年份', '俱乐部', '胜', '平', '负'])

历年成绩表

年份    俱乐部   胜   平   负
0  2010   巴塞罗那  30   6   2
1  2011   巴塞罗那  28   7   3
2  2012   巴塞罗那  32   4   2
3  2010  皇家马德里  29   5   4
4  2011  皇家马德里  32   4   2
5  2012  皇家马德里  26   7   5
6  2010   瓦伦西亚  21   8   9
7  2011   瓦伦西亚  17  10  11
8  2012   瓦伦西亚  19   8  11

In [3]:

当年名次 = np.array([1, 2, 1, 2, 1, 2, 3, 3, 3])
历年成绩表["当年名次"] = 当年名次

历年成绩表

年份    俱乐部   胜   平   负  当年名次
0  2010   巴塞罗那  30   6   2     1
1  2011   巴塞罗那  28   7   3     2
2  2012   巴塞罗那  32   4   2     1
3  2010  皇家马德里  29   5   4     2
4  2011  皇家马德里  32   4   2     1
5  2012  皇家马德里  26   7   5     2
6  2010   瓦伦西亚  21   8   9     3
7  2011   瓦伦西亚  17  10  11     3
8  2012   瓦伦西亚  19   8  11     3

In [6]:
# 基于索引值删除行。
历年成绩表.drop([0, 3, 6])

年份    俱乐部   胜   平   负  当年名次
1  2011   巴塞罗那  28   7   3     2
2  2012   巴塞罗那  32   4   2     1
4  2011  皇家马德里  32   4   2     1
5  2012  皇家马德里  26   7   5     2
7  2011   瓦伦西亚  17  10  11     3
8  2012   瓦伦西亚  19   8  11     3

In [8]:
历年成绩表.drop(['负', '平'], axis = 1)

年份    俱乐部   胜  当年名次
0  2010   巴塞罗那  30     1
1  2011   巴塞罗那  28     2
2  2012   巴塞罗那  32     1
3  2010  皇家马德里  29     2
4  2011  皇家马德里  32     1
5  2012  皇家马德里  26     2
6  2010   瓦伦西亚  21     3
7  2011   瓦伦西亚  17     3
8  2012   瓦伦西亚  19     3

In [10]:
历年成绩表.drop(历年成绩表.columns[3], axis = 1)       # 删除第3列。

年份    俱乐部   胜   负  当年名次
0  2010   巴塞罗那  30   2     1
1  2011   巴塞罗那  28   3     2
2  2012   巴塞罗那  32   2     1
3  2010  皇家马德里  29   4     2
4  2011  皇家马德里  32   2     1
5  2012  皇家马德里  26   5     2
6  2010   瓦伦西亚  21   9     3
7  2011   瓦伦西亚  17  11     3
8  2012   瓦伦西亚  19  11     3

In [12]:
历年成绩表.drop(历年成绩表.columns[[4, 3]], axis = 1)   # 删除第4、3列。

年份    俱乐部   胜  当年名次
0  2010   巴塞罗那  30     1
1  2011   巴塞罗那  28     2
2  2012   巴塞罗那  32     1
3  2010  皇家马德里  29     2
4  2011  皇家马德里  32     1
5  2012  皇家马德里  26     2
6  2010   瓦伦西亚  21     3
7  2011   瓦伦西亚  17     3
8  2012   瓦伦西亚  19     3

In [13]:
历年成绩表.drop(历年成绩表.index[1])     # 与“历年成绩表.drop[1]”相同。

年份    俱乐部   胜   平   负  当年名次
0  2010   巴塞罗那  30   6   2     1
2  2012   巴塞罗那  32   4   2     1
3  2010  皇家马德里  29   5   4     2
4  2011  皇家马德里  32   4   2     1
5  2012  皇家马德里  26   7   5     2
6  2010   瓦伦西亚  21   8   9     3
7  2011   瓦伦西亚  17  10  11     3
8  2012   瓦伦西亚  19   8  11     3

In [21]:
print("每个俱乐部名次的分布")
print("==================")

pd.crosstab(历年成绩表.俱乐部, 历年成绩表.当年名次)

每个俱乐部名次的分布


当年名次   1  2  3
俱乐部           
巴塞罗那   2  1  0
瓦伦西亚   0  0  3
皇家马德里  1  2  0

In [ ]:
读入的CSV文件 = pd.read_csv('data.csv')                   # 从CSV载入dataframe。
读入的CSV文件